# Generated by Django 5.0.1 on 2024-02-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
